### ISSUE TITLE
Add user to ModelDeveloper / Admin

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#33]
Hi @magraeber, 

Can we please add the following user as a ModelDeveloper (if that works) If not admin: 
- timo.schubert@danfoss.com
- 
The feature in Django doesnt work for us. 
![image](https://user-images.githubusercontent.com/45364510/216640862-fb60f360-c95b-4943-87e0-44897608cb68.png)

**Comment by magraeber** [comment]
Hi Stefan,

Yes, I have just added him.

I think it’s not working to change permissions of users by design. Otherwise you can elevate permissions yourself. You always need to write us and we do it as superadmin.

Best regards,
Manuel



Von: Stefan Walshe ***@***.***>
Gesendet: Freitag, 3. Februar 2023 16:26
An: tlkenergy/sim-tlk ***@***.***>
Cc: Manuel Gräber ***@***.***>; Mention ***@***.***>
Betreff: [tlkenergy/sim-tlk] Add user to ModelDeveloper / Admin (Issue #33)


Hi @magraeber<https://github.com/magraeber>,

Can we please add the following user as a ModelDeveloper (if that works) If not admin:

  *   ***@***.******@***.***>
  *

The feature in Django doesnt work for us.
[image]<https://user-images.githubusercontent.com/45364510/216640862-fb60f360-c95b-4943-87e0-44897608cb68.png>

**Comment by Walshest** [comment]
Hi, 
Thanks for getting back so quickly. Okay in future I will setup an issue like this. 
Thanks have a great weekend :)
